# Generated by Django 5.2 on 2025-04-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeUser',
            new_name='User',
        ),
    ]
